#指定使用哪个环境
spring: 
  profiles: 
    active: dev
---
#声明是开发环境
# spring: 
#   config: 
#     active: 
#       on-profile: dev
spring: 
  profiles: dev
  application: 
    name: sc-configcenter-dev
---
#声明是生产环境
# spring: 
#   config: 
#     active: 
#       on-profile: prod
spring:
  profiles: prod
  application: 
    name: sc-configcenter-prod
